# Docker Compose configuration for AI Architecture Advisor

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-architecture-advisor-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./learning-resources/notebooks:/home/jupyter/work/notebooks
      - ./learning-resources/examples/implementations:/home/jupyter/work/implementations
      - ./learning-resources/examples/tests:/home/jupyter/work/tests
      - ./ai-engine:/home/jupyter/work/ai-engine
      - ./commands:/home/jupyter/work/commands
      - ./data:/home/jupyter/work/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=ai-advisor-2025
    restart: unless-stopped
    networks:
      - ai-advisor-net

  # Optional: Add a service for running tests
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-architecture-advisor-tests
    command: python simple_test_runner.py
    volumes:
      - ./learning-resources/examples/implementations:/home/jupyter/work/implementations
      - ./learning-resources/examples/tests:/home/jupyter/work/tests
      - ./ai-engine:/home/jupyter/work/ai-engine
      - ./simple_test_runner.py:/home/jupyter/work/simple_test_runner.py
    profiles:
      - test
    networks:
      - ai-advisor-net

networks:
  ai-advisor-net:
    driver: bridge

volumes:
  jupyter-data: